name: Deploy to S3
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Slack Notification
      uses: act10ns/slack@v1
      with:
        status: starting
        channel: '#devops'
      if: always()

    - name: Checkout
      id: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Use Node.js 12
      id: setup
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Yarn Install
      id: yarn-install
      run: |
        yarn install 

    # - name: Staging Build
    #   id: yarn-build
    #   run: |
    #      yarn run build
  
    - name: slack status
      uses: act10ns/slack@v1
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#devops'
      if: always()

    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - run: aws s3 sync ./out s3://devopsbrothers.bucket.staging.us-east-1