on:
  workflow_dispatch:
name: InfraCost

env:
  INFRACOST_API_KEY : ${{secrets.INFRACOST_API_KEY}}
  AWS_ACCESS_KEY_ID : ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_KEY_ID : ${{secrets.AWS_SECRET_KEY_ID}}

jobs:
  infracost:
    runs-on: ubuntu-latest
  
    name: Run Infracost
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Terraform init
        run: |
          cd module
          terraform init
        working-directory: ${{ env.working-directory }}

      - name: Terraform plan
        run: terraform plan -out tfplan.binary
        working-directory: ${{ env.working-directory }}

      - name: Terraform show
        run: terraform show -json tfplan.binary > plan.json
        working-directory: ${{ env.working-directory }}

      - name: Setup Infracost
        uses: infracost/actions/setup@v1
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost JSON
        run: infracost breakdown --path plan.json --format json --out-file /tmp/infracost.json
        working-directory: ${{ env.working-directory }}
       
      - name: Post Infracost comment
        uses: infracost/actions/comment@v1
        with:
          path: /tmp/infracost.json
          behavior: update 
